# Generated by Django 3.1.3 on 2020-12-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduxationmain', '0004_auto_20201203_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsub',
            name='email',
            field=models.CharField(max_length=122),
        ),
    ]
