# Generated by Django 3.1.3 on 2020-12-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduxationmain', '0005_auto_20201203_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsub',
            name='email',
            field=models.EmailField(blank=True, max_length=122),
        ),
    ]
