# Generated by Django 3.1.3 on 2020-12-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduxationmain', '0006_auto_20201203_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsub',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
